sudo: false

language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 62@5.0.0 870 872

script:
- pio ci --board=uno --lib=. examples/AVR_NoteOnOffEverySec/AVR_NoteOnOffEverySec.ino examples/AVR_MinMemUsage/AVR_MinMemUsage.ino;
